### PR TITLE
5.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #40 - support Autofac 6.0 (@krajek)
 * #41 - improve test coverage (@krajek)

### CODE REVIEW

**Comment by batizar** [comment]
Waiting for this to be released to upgrade to Autofac 6!

**Comment by nblumhardt** [comment]
@batizar does the `5.0.0-dev` package work for you? Think we just need some smoke-test validation and this is good to go

**Comment by batizar** [comment]
@nblumhardt it was not crashing anymore, I didn't go farther than that, will test a bit more soon.

**Comment by nblumhardt** [comment]
@batizar thank you 😎

**Comment by batizar** [comment]
@nblumhardt I have used it in one of our apps in dev env and I haven't seen any issues so far.

 Is there any ETA for this? It is holding some of our planned upgrades, thanks.

**Comment by nblumhardt** [comment]
Thanks @batizar - published now 👍

**Pull request merged**
