### PR TITLE
Support .NET Core

### PR DESCRIPTION
**Pull request by mayuanyang**
AutofacSerilogIntegration

- The library itself support net4.5 and netestandard1.1
- Use Autofac version 4.0.0
- Use Serilog versioin 2.0.0
 
Example
The Example support netcoreapp1.0

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks Eddy! I'm going to merge and make a few changes to get CI back online.

**Comment by mayuanyang** [comment]
thanks, can see appveyor is failing, but cannot see the yml file, otherwise would uodate it as well

**Comment by nblumhardt** [comment]
:+1:

Published now, will give the -Pre version a few weeks to bake.

Cheers!

**Comment by mayuanyang** [comment]
great, thanks for your help

**Pull request merged**
