### PR TITLE
4.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #35 - improve performance by limiting unnecessary logger instantiations; adds `alwaysSupplyParameter` flag (@srogovtsev)

### CODE REVIEW

**Comment by srogovtsev** [comment]
It might be reasonable to bump up a major version: we're introducing a breaking change, even if small.

**Comment by srogovtsev** [comment]
> 
> 
>     * #36 - improve performance by limiting unnecessary logger instantiations; adds `alwaysSupplyParameter` flag (@srogovtsev)

I think this should be #35 (sorry for the mess with two PRs).

**Comment by srogovtsev** [comment]
Benchmarks:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18362.836 (1903/May2019Update/19H1)
Intel Core i7-7600U CPU 2.80GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4180.0), X86 LegacyJIT
  DefaultJob : .NET Framework 4.8 (4.8.4180.0), X86 LegacyJIT
```

|                | Reflection | ReflectionWithLogger | Instance | Delegate | TwoDelegates |
|--------------------- |---------:|----------:|----------:|------:|--------:|
| 3.0.0 | 1.00 | 2.29 | 0.83 | **1.96** | **3.43** |
| 3.1.0-dev-00037 | 1.00 | 2.27 | 0.82 | **0.89** | **1.20** |

**Comment by nblumhardt** [comment]
Thanks for spotting those two things, fixed now 👍 

Benchmarks are looking good 😎

**Comment by srogovtsev** [comment]
Sorry for bumping this up, but can we get a public release within a couple of weeks? It's just that the release of the product I'm using this in is in mid-August, and I'd prefer to go live with public dependency instead of a preview one.

**Comment by nblumhardt** [comment]
Done! Thanks, and good luck!

**Pull request merged**
